services:
  # Backend API Service (Now also runs the scheduler)
  - type: web
    name: sentiment-api-final
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/tickers
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sentiment-db
          property: connectionString
      - key: STARTUP_COMMAND
        value: api
      - key: NEWS_API_KEY
        sync: false

  # Frontend Service (Streamlit)
  - type: web
    name: sentiment-frontend-final
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sentiment-db
          property: connectionString
      - key: STARTUP_COMMAND
        value: frontend
      - key: NEWS_API_KEY
        sync: false

databases:
  # Free PostgreSQL Database
  - name: sentiment-db
    plan: free
